#!/bin/bash

r=$(readlink "$0")
if [ -n "$r" ]; then
  cd $(dirname "$r")
else
  cd $(dirname "$0")
fi

node=$(which node 2>/dev/null)
if [ -z "$node" ]; then
  node="/usr/local/bin/node"
  if [ ! -f "$node" ]; then
    echo "Node not found."
    exit 1
  fi
fi

killall node > /dev/null 2>&1 && sleep 2
killall dilated > /dev/null 2>&1 && sleep 2

case "$1" in
  production | --production)
    if [ $(id -u) -ne 0 ]; then
      echo "You probably want root privelages."
      exit 1
    fi
    export NODE_ENV=production
    # daemonize...kind of
    (setsid "$node" ./server > /dev/null 2>&1 &)
  ;;
  * | dev | --dev)
    export NODE_ENV=development
    exec "$node" ./server
  ;;
esac
